version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment: 
      - POSTGRES_USER=ttrss
      - POSTGRES_PASSWORD=ttrss
      - POSTGRES_DB=ttrss
    volumes:
      - /mnt/Data/postgresql:/var/lib/postgresql/data
  ttrss_test:
    image: ttrss
    container_name: ttrss
    build: .
    restart: always
    ports: 
      - "3000:3000"
    command: /var/startup.sh
    depends_on: 
      - postgres
